name: Update

on:
  schedule:
    - cron: 0 0 * * *

jobs:
  update:
    name: Update
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Install nix
        uses: nixbuild/nix-quick-install-action@v34

      - name: Clone repository
        uses: actions/checkout@v5

      - name: Update inputs
        run: bin/update

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          test -n "$(git status --porcelain)" || exit 0
          git commit --message="Update inputs"
          git push
